# random-normal

In [1]:
import tensorflow as tf

In [9]:
# 所取值不一定非在[2,3]间
a = tf.random.normal([2,3], mean=0.5, stddev=1)
print("a:",a)

a: tf.Tensor(
[[ 3.6648624  1.063337   2.0807095]
 [ 2.0119984 -1.8328631 -1.1814233]], shape=(2, 3), dtype=float32)


In [12]:
# 所取值一定要在[2,3]间，如有超出重取
e = tf.random.truncated_normal([2,3], mean=0.5, stddev=1)
print("e:",e)

e: tf.Tensor(
[[-0.60818577  0.9905755   0.9412654 ]
 [ 0.26507697 -0.8701589  -0.25461513]], shape=(2, 3), dtype=float32)
