In [2]:
import tensorflow as tf

In [3]:
x =  tf.constant([[1,2,4],[2,3,4]])
print("x:",x)
# 求X中所有数的均值
print("mean of x:", tf.reduce_mean(x))
# 求每一行的和
print("sum of x:", tf.reduce_sum(x, axis=1))

x: tf.Tensor(
[[1 2 4]
 [2 3 4]], shape=(2, 3), dtype=int32)
mean of x: tf.Tensor(2, shape=(), dtype=int32)
sum of x: tf.Tensor([7 9], shape=(2,), dtype=int32)
