In [2]:
import tensorflow as tf
import numpy as np

SEED = 23455

rdm = np.random.RandomState(seed=SEED)  # 生成[0,1)之间的随机数
x = rdm.rand(32, 2)
y_ = [[x1 + x2 + (rdm.rand() / 10.0 - 0.05)] for (x1, x2) in x]  # 生成噪声[0,1)/10=[0,0.1); [0,0.1)-0.05=[-0.05,0.05)
x = tf.cast(x, dtype=tf.float32)

w1 = tf.Variable(tf.random.normal([2, 1], stddev=1, seed=1))

epoch = 15000
lr = 0.002

for epoch in range(epoch):
    with tf.GradientTape() as tape:
        y = tf.matmul(x, w1)
        loss_mse = tf.reduce_mean(tf.square(y_ - y))

    grads = tape.gradient(loss_mse, w1)
    w1.assign_sub(lr * grads)

    if epoch % 500 == 0:
        print("After %d training steps,w1 is " % (epoch))
        print(w1.numpy(), "\n")
print("Final w1 is: ", w1.numpy())

After 0 training steps,w1 is 
[[1.3587625]
 [0.5420639]] 

After 500 training steps,w1 is 
[[1.3290828]
 [0.6622308]] 

After 1000 training steps,w1 is 
[[1.2821434 ]
 [0.73504746]] 

After 1500 training steps,w1 is 
[[1.236049  ]
 [0.78612137]] 

After 2000 training steps,w1 is 
[[1.1956878]
 [0.8251068]] 

After 2500 training steps,w1 is 
[[1.1617233 ]
 [0.85610765]] 

After 3000 training steps,w1 is 
[[1.1335756 ]
 [0.88120794]] 

After 3500 training steps,w1 is 
[[1.1103905]
 [0.9016864]] 

After 4000 training steps,w1 is 
[[1.0913397 ]
 [0.91844666]] 

After 4500 training steps,w1 is 
[[1.0757021 ]
 [0.93218184]] 

After 5000 training steps,w1 is 
[[1.0628718]
 [0.9434442]] 

After 5500 training steps,w1 is 
[[1.0523463]
 [0.9526807]] 

After 6000 training steps,w1 is 
[[1.0437124]
 [0.9602566]] 

After 6500 training steps,w1 is 
[[1.0366298 ]
 [0.96647066]] 

After 7000 training steps,w1 is 
[[1.0308208]
 [0.9715677]] 

After 7500 training steps,w1 is 
[[1.0260557]
 [0.9757484]] 