In [1]:
import tensorflow as tf
import numpy as np

In [2]:
# 自定义损失函数
# 酸奶成本1元， 酸奶利润99元
# 成本很低，利润很高，人们希望多预测些，生成模型系数大于1，往多了预测

SEED = 23455
COST = 1
PROFIT = 99

rdm = np.random.RandomState(SEED)
x = rdm.rand(32, 2)
y_ = [[x1 + x2 + (rdm.rand() / 10.0 - 0.05)] for (x1, x2) in x]  # 生成噪声[0,1)/10=[0,0.1); [0,0.1)-0.05=[-0.05,0.05)
x = tf.cast(x, dtype=tf.float32)

w1 = tf.Variable(tf.random.normal([2, 1], stddev=1, seed=1))

epoch = 10000
lr = 0.002

for epoch in range(epoch):
    with tf.GradientTape() as tape:
        y = tf.matmul(x, w1)
        loss = tf.reduce_sum(tf.where(tf.greater(y, y_), (y - y_) * COST, (y_ - y) * PROFIT))

    grads = tape.gradient(loss, w1)
    w1.assign_sub(lr * grads)

    if epoch % 500 == 0:
        print("After %d training steps,w1 is " % (epoch))
        print(w1.numpy(), "\n")
print("Final w1 is: ", w1.numpy())

After 0 training steps,w1 is 
[[2.0855923]
 [3.8476257]] 

After 500 training steps,w1 is 
[[1.1830753]
 [1.1627482]] 

After 1000 training steps,w1 is 
[[1.1526372]
 [1.0175619]] 

After 1500 training steps,w1 is 
[[1.1430172]
 [1.0488456]] 

After 2000 training steps,w1 is 
[[1.1333971]
 [1.0801294]] 

After 2500 training steps,w1 is 
[[1.1237767]
 [1.1114128]] 

After 3000 training steps,w1 is 
[[1.1727899]
 [1.1539897]] 

After 3500 training steps,w1 is 
[[1.1423519]
 [1.0088034]] 

After 4000 training steps,w1 is 
[[1.132732 ]
 [1.0400873]] 

After 4500 training steps,w1 is 
[[1.1231122]
 [1.0713713]] 

After 5000 training steps,w1 is 
[[1.1134921]
 [1.102655 ]] 

After 5500 training steps,w1 is 
[[1.1625056]
 [1.1452322]] 

After 6000 training steps,w1 is 
[[1.1528853]
 [1.1765157]] 

After 6500 training steps,w1 is 
[[1.122447 ]
 [1.0313292]] 

After 7000 training steps,w1 is 
[[1.112827 ]
 [1.0626129]] 

After 7500 training steps,w1 is 
[[1.1618403]
 [1.1051899]] 

After 8000 t